### ISSUE TITLE
Crashing after uninstalling 

### ISSUE THREAD

**Issue by Lightluc** [Sarenor/Ars-Instrumentum#6]
I added this mod to my ATM 7 server, and then deleted it the next day, and now one of the players is crashing a bit after they log on. Im sorry if I'm doing this wrong, I'm new to all of this :(

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry Object not present: ars_instrumentum:wizards_armarium
Exit Code: -1

[crash-2022-08-20_20.56.36-client.txt](https://github.com/Sarenor/Ars-Instrumentum/files/9388288/crash-2022-08-20_20.56.36-client.txt)

**Comment by Sarenor** [comment]
Managed to read the crashlog on my phone: The Player has Ars Instrumentum still installed and therefore the keybind listener is still active.
They're triggering one of the Armarium Keybinds and it tries to get the Armarium Item instance, but since the server doesn't have the mod anymore it doesn't exist, can't be accessed and crashes.

Simply have your player remove Ars Instrumentum as well (or if they want to keep it for their singleplayer worlds, have them unbind the keybindings for the Armarium so they can't be triggered by accident)

Out of curiosity: Why did you decide to remove AI again?

**Comment by Lightluc** [comment]
I mostly installed it to see my mana, I uninstalled it because a few of the server members didn't want to go through the "hassle" of installing it instead of just clicking play on ATM7 (the modpack we are playing)

**Comment by Lightluc** [comment]
ALSO THANK YOU !

**Comment by Sarenor** [comment]
No problem. I did that to myself during development often enough!
Have fun!
